# Controls when the action will run. 
on:
  # Triggers the workflow on push events to the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile Updated Website
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Node v14.#.#
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Compiling website
        run: |
          node ./bin/cli compile
          echo "Stash release files up 1 directory"
          mv release/ ../release
      
      - name: Checkout website branch
        uses: actions/checkout@v2
        with:
          ref: website

      - name: Pushing to gh pages
        run: |
          git config --global user.name 'Caboodle Tech Inc'
          git config --global user.email 'blizzardengle@users.noreply.github.com'
          rm *
          ehco "Copy release files into website branch"
          cp ../release/* .
          rm ../release -r
          git add .
          git commit -m "auto update"
          git push