# Controls when the action will run. 
on:
  # Triggers the workflow on push events to the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Start Setup
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: cd bin && node cli compile
      - run: echo "Test Done"
